#!/usr/bin/env bash
# print "Best School" ten times and "Hi" one time.

i=1

while [ "$i" -le 10 ]
do
  if [ "$i" == 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  i=$((i+1))
done
