#!/bin/bash

# Define the key name
KEY_NAME="school"

# Define the key size
KEY_SIZE=4096

# Define the passphrase
PASSPHRASE="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b $KEY_SIZE -f $KEY_NAME -N $PASSPHRASE

